### ISSUE TITLE
Can't connect to MQTT Broker

### ISSUE THREAD

**Issue by Smarthome-Creator** [rubenpeters91/rgb2mqtt#10]
Hello,

I wanted to set up the script today and it actually does what it should except that it connects to my MQTT broker.
Here is an excerpt from the log:

`PS C:\Users\Try> rgb2mqtt-run -v
2024-11-16 19:47:45,980 INFO: Connecting to MQTT client...
2024-11-16 19:47:45,985 INFO: Connecting to OpenRGB server...
2024-11-16 19:47:45,990 INFO: Connection to OpenRGB succeeded!
2024-11-16 19:47:46,005 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:48,019 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:50,028 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:52,039 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:54,078 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:56,088 INFO: Connected to MQTT client with result code 0
2024-11-16 19:47:58,100 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:00,124 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:02,131 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:04,158 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:06,171 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:08,182 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:10,191 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:12,202 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:14,213 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:16,222 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:18,232 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:20,251 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:22,284 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:24,317 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:26,358 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:28,359 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:30,367 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:32,376 INFO: Connected to MQTT client with result code 0
2024-11-16 19:48:34,387 INFO: Connected to MQTT client with result code 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Try\AppData\Local\Programs\Python\Python312\Scripts\rgb2mqtt-run.exe\__main__.py", line 7, in <module>
  File "C:\Users\Try\AppData\Local\Programs\Python\Python312\Lib\site-packages\rgb2mqtt\run.py", line 128, in run_rgb2mqtt
    mqtt_client.loop_forever()
  File "C:\Users\Try\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 1773, in loop_forever
    self._reconnect_wait()
  File "C:\Users\Try\AppData\Local\Programs\Python\Python312\Lib\site-packages\paho\mqtt\client.py", line 3612, in _reconnect_wait
    time.sleep(min(remaining, 1))
KeyboardInterrupt
PS C:\Users\Try>`

Is this a bug in the script or is it on the client side?

Otherwise, thank you for keeping the project alive.

**Comment by rubenpeters91** [comment]
Hey sorry for the late reply, it's hard for me to debug what's going wrong. Where is your MQTT server running? Is it reachable from the device where you run this script?

**Comment by Smarthome-Creator** [comment]
Thanks for your reply, let me try to explain the problem. When I start the script with "-v" I get this messages:
<img width="689" alt="Bildschirmfoto 2024-11-28 um 18 18 22" src="https://github.com/user-attachments/assets/89581249-b04e-4716-bbe4-b2fbba21c432">

I think all connection established and working, the script is connected to OpenRGB:
<img width="339" alt="Bildschirmfoto 2024-11-28 um 18 25 19" src="https://github.com/user-attachments/assets/411bce65-0b55-452d-8b47-ed956b59c42e">

But no new device is discovered in Home Assistant. (I used Mosquitto on my Home Assistant server.)
I think the new device should be the name "Spiele-PC RGB-MQTT", same like show in OpenRGB?
This is my current config file:
<img width="340" alt="Bildschirmfoto 2024-11-28 um 18 34 29" src="https://github.com/user-attachments/assets/767da24e-978b-45a7-8196-0b0d7230ff68">

And this happens when I stop the script:
<img width="935" alt="Bildschirmfoto 2024-11-28 um 18 37 22" src="https://github.com/user-attachments/assets/d54c90e4-03b1-4f20-9886-1c62366feec2">

I'm not sure it is an issue. You have an idea or I have a configuration issue?

**Comment by rubenpeters91** [comment]
Check, so the script is both connected to openRGB and your mosquitto broker. Are you using the MQTT integration in Home Assistant (see: https://www.home-assistant.io/integrations/mqtt)? Auto-discovery should be on by default, so any new topic should be automatically added to HA as a light. 

Maybe check the logs of the MQTT integration, or see if you can use the configuration page of the integration to listen to specific messages. Specifically when starting the script, all connected devices should send their state, so the MQTT integration should receive messages on: `homeassistant/light/device_name/state` (in your case e.g. `homeassistant/light/Keyboard/state`). 

Let me know if this helps!

**Comment by Smarthome-Creator** [comment]
I have a few new findings after a few tests. I used MQTT-Explorer to see what the Mosquitto receives.
I can see my RGB devices from my main Windows 11 system but only for 1 Second. After updating the MQTT Explorer, the devices are no longer visible.

In other words, the script is puplishing my devices, but then seems to crash and disconnects from the broker before the devices can be discovered by the broker.

I have checked this with my old Windows 10 laptop and all connections are stable and I can use my devices in HA via MQTT.
Do you have any ideas where I could look for the problem? Are you a Windows user?

The only other thing I can think of is that a manufacturer's software on my main system is causing the problem.
I don't have any such software on my laptop...
I'll give that a try.
